// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osapi-io/osapi/internal/job/client (interfaces: AgentKeyStore)
//
// Generated by this command:
//
//	mockgen -destination=./agent_key_store.gen.go -package=mocks github.com/osapi-io/osapi/internal/job/client AgentKeyStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	client "github.com/osapi-io/osapi/internal/job/client"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentKeyStore is a mock of AgentKeyStore interface.
type MockAgentKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockAgentKeyStoreMockRecorder
	isgomock struct{}
}

// MockAgentKeyStoreMockRecorder is the mock recorder for MockAgentKeyStore.
type MockAgentKeyStoreMockRecorder struct {
	mock *MockAgentKeyStore
}

// NewMockAgentKeyStore creates a new mock instance.
func NewMockAgentKeyStore(ctrl *gomock.Controller) *MockAgentKeyStore {
	mock := &MockAgentKeyStore{ctrl: ctrl}
	mock.recorder = &MockAgentKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentKeyStore) EXPECT() *MockAgentKeyStoreMockRecorder {
	return m.recorder
}

// LookupAgentKey mocks base method.
func (m *MockAgentKeyStore) LookupAgentKey(ctx context.Context, machineID string) (*client.AgentKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupAgentKey", ctx, machineID)
	ret0, _ := ret[0].(*client.AgentKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupAgentKey indicates an expected call of LookupAgentKey.
func (mr *MockAgentKeyStoreMockRecorder) LookupAgentKey(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupAgentKey", reflect.TypeOf((*MockAgentKeyStore)(nil).LookupAgentKey), ctx, machineID)
}
