// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/job/client (interfaces: JobClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
	client "github.com/osapi-io/nats-client/pkg/client"
	job "github.com/retr0h/osapi/internal/job"
	client0 "github.com/retr0h/osapi/internal/job/client"
)

// MockJobClient is a mock of JobClient interface.
type MockJobClient struct {
	ctrl     *gomock.Controller
	recorder *MockJobClientMockRecorder
}

// MockJobClientMockRecorder is the mock recorder for MockJobClient.
type MockJobClientMockRecorder struct {
	mock *MockJobClient
}

// NewMockJobClient creates a new mock instance.
func NewMockJobClient(ctrl *gomock.Controller) *MockJobClient {
	mock := &MockJobClient{ctrl: ctrl}
	mock.recorder = &MockJobClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobClient) EXPECT() *MockJobClientMockRecorder {
	return m.recorder
}

// CheckDrainFlag mocks base method.
func (m *MockJobClient) CheckDrainFlag(arg0 context.Context, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDrainFlag", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckDrainFlag indicates an expected call of CheckDrainFlag.
func (mr *MockJobClientMockRecorder) CheckDrainFlag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDrainFlag", reflect.TypeOf((*MockJobClient)(nil).CheckDrainFlag), arg0, arg1)
}

// ConsumeJobs mocks base method.
func (m *MockJobClient) ConsumeJobs(arg0 context.Context, arg1, arg2 string, arg3 func(jetstream.Msg) error, arg4 *client.ConsumeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeJobs", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeJobs indicates an expected call of ConsumeJobs.
func (mr *MockJobClientMockRecorder) ConsumeJobs(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeJobs", reflect.TypeOf((*MockJobClient)(nil).ConsumeJobs), arg0, arg1, arg2, arg3, arg4)
}

// CreateOrUpdateConsumer mocks base method.
func (m *MockJobClient) CreateOrUpdateConsumer(arg0 context.Context, arg1 string, arg2 jetstream.ConsumerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateConsumer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateConsumer indicates an expected call of CreateOrUpdateConsumer.
func (mr *MockJobClientMockRecorder) CreateOrUpdateConsumer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateConsumer", reflect.TypeOf((*MockJobClient)(nil).CreateOrUpdateConsumer), arg0, arg1, arg2)
}

// DeleteDrainFlag mocks base method.
func (m *MockJobClient) DeleteDrainFlag(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDrainFlag", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDrainFlag indicates an expected call of DeleteDrainFlag.
func (mr *MockJobClientMockRecorder) DeleteDrainFlag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDrainFlag", reflect.TypeOf((*MockJobClient)(nil).DeleteDrainFlag), arg0, arg1)
}

// DeleteJob mocks base method.
func (m *MockJobClient) DeleteJob(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockJobClientMockRecorder) DeleteJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockJobClient)(nil).DeleteJob), arg0, arg1)
}

// GetAgent mocks base method.
func (m *MockJobClient) GetAgent(arg0 context.Context, arg1 string) (*job.AgentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", arg0, arg1)
	ret0, _ := ret[0].(*job.AgentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockJobClientMockRecorder) GetAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockJobClient)(nil).GetAgent), arg0, arg1)
}

// GetAgentTimeline mocks base method.
func (m *MockJobClient) GetAgentTimeline(arg0 context.Context, arg1 string) ([]job.TimelineEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentTimeline", arg0, arg1)
	ret0, _ := ret[0].([]job.TimelineEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentTimeline indicates an expected call of GetAgentTimeline.
func (mr *MockJobClientMockRecorder) GetAgentTimeline(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentTimeline", reflect.TypeOf((*MockJobClient)(nil).GetAgentTimeline), arg0, arg1)
}

// GetJobData mocks base method.
func (m *MockJobClient) GetJobData(arg0 context.Context, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobData", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobData indicates an expected call of GetJobData.
func (mr *MockJobClientMockRecorder) GetJobData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobData", reflect.TypeOf((*MockJobClient)(nil).GetJobData), arg0, arg1)
}

// GetJobStatus mocks base method.
func (m *MockJobClient) GetJobStatus(arg0 context.Context, arg1 string) (*job.QueuedJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", arg0, arg1)
	ret0, _ := ret[0].(*job.QueuedJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockJobClientMockRecorder) GetJobStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockJobClient)(nil).GetJobStatus), arg0, arg1)
}

// GetQueueSummary mocks base method.
func (m *MockJobClient) GetQueueSummary(arg0 context.Context) (*job.QueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueSummary", arg0)
	ret0, _ := ret[0].(*job.QueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueSummary indicates an expected call of GetQueueSummary.
func (mr *MockJobClientMockRecorder) GetQueueSummary(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueSummary", reflect.TypeOf((*MockJobClient)(nil).GetQueueSummary), arg0)
}

// ListAgents mocks base method.
func (m *MockJobClient) ListAgents(arg0 context.Context) ([]job.AgentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", arg0)
	ret0, _ := ret[0].([]job.AgentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockJobClientMockRecorder) ListAgents(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockJobClient)(nil).ListAgents), arg0)
}

// ListJobs mocks base method.
func (m *MockJobClient) ListJobs(arg0 context.Context, arg1 string, arg2, arg3 int) (*client0.ListJobsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*client0.ListJobsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobClientMockRecorder) ListJobs(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobClient)(nil).ListJobs), arg0, arg1, arg2, arg3)
}

// Modify mocks base method.
func (m *MockJobClient) Modify(arg0 context.Context, arg1, arg2, arg3 string, arg4 interface{}) (string, *job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Modify", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Modify indicates an expected call of Modify.
func (mr *MockJobClientMockRecorder) Modify(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Modify", reflect.TypeOf((*MockJobClient)(nil).Modify), arg0, arg1, arg2, arg3, arg4)
}

// ModifyBroadcast mocks base method.
func (m *MockJobClient) ModifyBroadcast(arg0 context.Context, arg1, arg2, arg3 string, arg4 interface{}) (string, map[string]*job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyBroadcast", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ModifyBroadcast indicates an expected call of ModifyBroadcast.
func (mr *MockJobClientMockRecorder) ModifyBroadcast(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyBroadcast", reflect.TypeOf((*MockJobClient)(nil).ModifyBroadcast), arg0, arg1, arg2, arg3, arg4)
}

// Query mocks base method.
func (m *MockJobClient) Query(arg0 context.Context, arg1, arg2, arg3 string, arg4 interface{}) (string, *job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockJobClientMockRecorder) Query(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockJobClient)(nil).Query), arg0, arg1, arg2, arg3, arg4)
}

// QueryBroadcast mocks base method.
func (m *MockJobClient) QueryBroadcast(arg0 context.Context, arg1, arg2, arg3 string, arg4 interface{}) (string, map[string]*job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryBroadcast", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryBroadcast indicates an expected call of QueryBroadcast.
func (mr *MockJobClientMockRecorder) QueryBroadcast(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryBroadcast", reflect.TypeOf((*MockJobClient)(nil).QueryBroadcast), arg0, arg1, arg2, arg3, arg4)
}

// RetryJob mocks base method.
func (m *MockJobClient) RetryJob(arg0 context.Context, arg1, arg2 string) (*client0.CreateJobResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryJob", arg0, arg1, arg2)
	ret0, _ := ret[0].(*client0.CreateJobResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetryJob indicates an expected call of RetryJob.
func (mr *MockJobClientMockRecorder) RetryJob(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryJob", reflect.TypeOf((*MockJobClient)(nil).RetryJob), arg0, arg1, arg2)
}

// SetDrainFlag mocks base method.
func (m *MockJobClient) SetDrainFlag(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDrainFlag", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDrainFlag indicates an expected call of SetDrainFlag.
func (mr *MockJobClientMockRecorder) SetDrainFlag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDrainFlag", reflect.TypeOf((*MockJobClient)(nil).SetDrainFlag), arg0, arg1)
}

// WriteAgentTimelineEvent mocks base method.
func (m *MockJobClient) WriteAgentTimelineEvent(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAgentTimelineEvent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAgentTimelineEvent indicates an expected call of WriteAgentTimelineEvent.
func (mr *MockJobClientMockRecorder) WriteAgentTimelineEvent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAgentTimelineEvent", reflect.TypeOf((*MockJobClient)(nil).WriteAgentTimelineEvent), arg0, arg1, arg2, arg3)
}

// WriteJobResponse mocks base method.
func (m *MockJobClient) WriteJobResponse(arg0 context.Context, arg1, arg2 string, arg3 []byte, arg4, arg5 string, arg6 *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJobResponse", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJobResponse indicates an expected call of WriteJobResponse.
func (mr *MockJobClientMockRecorder) WriteJobResponse(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJobResponse", reflect.TypeOf((*MockJobClient)(nil).WriteJobResponse), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// WriteStatusEvent mocks base method.
func (m *MockJobClient) WriteStatusEvent(arg0 context.Context, arg1, arg2, arg3 string, arg4 map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteStatusEvent", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteStatusEvent indicates an expected call of WriteStatusEvent.
func (mr *MockJobClientMockRecorder) WriteStatusEvent(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteStatusEvent", reflect.TypeOf((*MockJobClient)(nil).WriteStatusEvent), arg0, arg1, arg2, arg3, arg4)
}
