// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/job/client (interfaces: JobClient)
//
// Generated by this command:
//
//	mockgen -destination=./job_client.gen.go -package=mocks github.com/retr0h/osapi/internal/job/client JobClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jetstream "github.com/nats-io/nats.go/jetstream"
	client "github.com/osapi-io/nats-client/pkg/client"
	job "github.com/retr0h/osapi/internal/job"
	client0 "github.com/retr0h/osapi/internal/job/client"
	gomock "go.uber.org/mock/gomock"
)

// MockJobClient is a mock of JobClient interface.
type MockJobClient struct {
	ctrl     *gomock.Controller
	recorder *MockJobClientMockRecorder
	isgomock struct{}
}

// MockJobClientMockRecorder is the mock recorder for MockJobClient.
type MockJobClientMockRecorder struct {
	mock *MockJobClient
}

// NewMockJobClient creates a new mock instance.
func NewMockJobClient(ctrl *gomock.Controller) *MockJobClient {
	mock := &MockJobClient{ctrl: ctrl}
	mock.recorder = &MockJobClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobClient) EXPECT() *MockJobClientMockRecorder {
	return m.recorder
}

// CheckDrainFlag mocks base method.
func (m *MockJobClient) CheckDrainFlag(ctx context.Context, hostname string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDrainFlag", ctx, hostname)
	ret0, _ := ret[0].(bool)
	return ret0
}

// CheckDrainFlag indicates an expected call of CheckDrainFlag.
func (mr *MockJobClientMockRecorder) CheckDrainFlag(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDrainFlag", reflect.TypeOf((*MockJobClient)(nil).CheckDrainFlag), ctx, hostname)
}

// ConsumeJobs mocks base method.
func (m *MockJobClient) ConsumeJobs(ctx context.Context, streamName, consumerName string, handler func(jetstream.Msg) error, opts *client.ConsumeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeJobs", ctx, streamName, consumerName, handler, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeJobs indicates an expected call of ConsumeJobs.
func (mr *MockJobClientMockRecorder) ConsumeJobs(ctx, streamName, consumerName, handler, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeJobs", reflect.TypeOf((*MockJobClient)(nil).ConsumeJobs), ctx, streamName, consumerName, handler, opts)
}

// CreateOrUpdateConsumer mocks base method.
func (m *MockJobClient) CreateOrUpdateConsumer(ctx context.Context, streamName string, consumerConfig jetstream.ConsumerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateConsumer", ctx, streamName, consumerConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateConsumer indicates an expected call of CreateOrUpdateConsumer.
func (mr *MockJobClientMockRecorder) CreateOrUpdateConsumer(ctx, streamName, consumerConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateConsumer", reflect.TypeOf((*MockJobClient)(nil).CreateOrUpdateConsumer), ctx, streamName, consumerConfig)
}

// DeleteDrainFlag mocks base method.
func (m *MockJobClient) DeleteDrainFlag(ctx context.Context, hostname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDrainFlag", ctx, hostname)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDrainFlag indicates an expected call of DeleteDrainFlag.
func (mr *MockJobClientMockRecorder) DeleteDrainFlag(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDrainFlag", reflect.TypeOf((*MockJobClient)(nil).DeleteDrainFlag), ctx, hostname)
}

// DeleteJob mocks base method.
func (m *MockJobClient) DeleteJob(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockJobClientMockRecorder) DeleteJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockJobClient)(nil).DeleteJob), ctx, jobID)
}

// GetAgent mocks base method.
func (m *MockJobClient) GetAgent(ctx context.Context, hostname string) (*job.AgentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgent", ctx, hostname)
	ret0, _ := ret[0].(*job.AgentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgent indicates an expected call of GetAgent.
func (mr *MockJobClientMockRecorder) GetAgent(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgent", reflect.TypeOf((*MockJobClient)(nil).GetAgent), ctx, hostname)
}

// GetAgentTimeline mocks base method.
func (m *MockJobClient) GetAgentTimeline(ctx context.Context, hostname string) ([]job.TimelineEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentTimeline", ctx, hostname)
	ret0, _ := ret[0].([]job.TimelineEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentTimeline indicates an expected call of GetAgentTimeline.
func (mr *MockJobClientMockRecorder) GetAgentTimeline(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentTimeline", reflect.TypeOf((*MockJobClient)(nil).GetAgentTimeline), ctx, hostname)
}

// GetJobData mocks base method.
func (m *MockJobClient) GetJobData(ctx context.Context, jobKey string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobData", ctx, jobKey)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobData indicates an expected call of GetJobData.
func (mr *MockJobClientMockRecorder) GetJobData(ctx, jobKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobData", reflect.TypeOf((*MockJobClient)(nil).GetJobData), ctx, jobKey)
}

// GetJobStatus mocks base method.
func (m *MockJobClient) GetJobStatus(ctx context.Context, jobID string) (*job.QueuedJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", ctx, jobID)
	ret0, _ := ret[0].(*job.QueuedJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockJobClientMockRecorder) GetJobStatus(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockJobClient)(nil).GetJobStatus), ctx, jobID)
}

// GetQueueSummary mocks base method.
func (m *MockJobClient) GetQueueSummary(ctx context.Context) (*job.QueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueSummary", ctx)
	ret0, _ := ret[0].(*job.QueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueSummary indicates an expected call of GetQueueSummary.
func (mr *MockJobClientMockRecorder) GetQueueSummary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueSummary", reflect.TypeOf((*MockJobClient)(nil).GetQueueSummary), ctx)
}

// ListAgents mocks base method.
func (m *MockJobClient) ListAgents(ctx context.Context) ([]job.AgentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAgents", ctx)
	ret0, _ := ret[0].([]job.AgentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAgents indicates an expected call of ListAgents.
func (mr *MockJobClientMockRecorder) ListAgents(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAgents", reflect.TypeOf((*MockJobClient)(nil).ListAgents), ctx)
}

// ListJobs mocks base method.
func (m *MockJobClient) ListJobs(ctx context.Context, statusFilter string, limit, offset int) (*client0.ListJobsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", ctx, statusFilter, limit, offset)
	ret0, _ := ret[0].(*client0.ListJobsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobClientMockRecorder) ListJobs(ctx, statusFilter, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobClient)(nil).ListJobs), ctx, statusFilter, limit, offset)
}

// Modify mocks base method.
func (m *MockJobClient) Modify(ctx context.Context, target, category string, operation job.OperationType, data any) (string, *job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Modify", ctx, target, category, operation, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Modify indicates an expected call of Modify.
func (mr *MockJobClientMockRecorder) Modify(ctx, target, category, operation, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Modify", reflect.TypeOf((*MockJobClient)(nil).Modify), ctx, target, category, operation, data)
}

// ModifyBroadcast mocks base method.
func (m *MockJobClient) ModifyBroadcast(ctx context.Context, target, category string, operation job.OperationType, data any) (string, map[string]*job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyBroadcast", ctx, target, category, operation, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ModifyBroadcast indicates an expected call of ModifyBroadcast.
func (mr *MockJobClientMockRecorder) ModifyBroadcast(ctx, target, category, operation, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyBroadcast", reflect.TypeOf((*MockJobClient)(nil).ModifyBroadcast), ctx, target, category, operation, data)
}

// Query mocks base method.
func (m *MockJobClient) Query(ctx context.Context, target, category string, operation job.OperationType, data any) (string, *job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, target, category, operation, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Query indicates an expected call of Query.
func (mr *MockJobClientMockRecorder) Query(ctx, target, category, operation, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockJobClient)(nil).Query), ctx, target, category, operation, data)
}

// QueryBroadcast mocks base method.
func (m *MockJobClient) QueryBroadcast(ctx context.Context, target, category string, operation job.OperationType, data any) (string, map[string]*job.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryBroadcast", ctx, target, category, operation, data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*job.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryBroadcast indicates an expected call of QueryBroadcast.
func (mr *MockJobClientMockRecorder) QueryBroadcast(ctx, target, category, operation, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryBroadcast", reflect.TypeOf((*MockJobClient)(nil).QueryBroadcast), ctx, target, category, operation, data)
}

// RetryJob mocks base method.
func (m *MockJobClient) RetryJob(ctx context.Context, jobID, targetHostname string) (*client0.CreateJobResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryJob", ctx, jobID, targetHostname)
	ret0, _ := ret[0].(*client0.CreateJobResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetryJob indicates an expected call of RetryJob.
func (mr *MockJobClientMockRecorder) RetryJob(ctx, jobID, targetHostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryJob", reflect.TypeOf((*MockJobClient)(nil).RetryJob), ctx, jobID, targetHostname)
}

// SetDrainFlag mocks base method.
func (m *MockJobClient) SetDrainFlag(ctx context.Context, hostname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDrainFlag", ctx, hostname)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDrainFlag indicates an expected call of SetDrainFlag.
func (mr *MockJobClientMockRecorder) SetDrainFlag(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDrainFlag", reflect.TypeOf((*MockJobClient)(nil).SetDrainFlag), ctx, hostname)
}

// WriteAgentTimelineEvent mocks base method.
func (m *MockJobClient) WriteAgentTimelineEvent(ctx context.Context, hostname, event, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAgentTimelineEvent", ctx, hostname, event, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAgentTimelineEvent indicates an expected call of WriteAgentTimelineEvent.
func (mr *MockJobClientMockRecorder) WriteAgentTimelineEvent(ctx, hostname, event, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAgentTimelineEvent", reflect.TypeOf((*MockJobClient)(nil).WriteAgentTimelineEvent), ctx, hostname, event, message)
}

// WriteJobResponse mocks base method.
func (m *MockJobClient) WriteJobResponse(ctx context.Context, jobID, hostname string, responseData []byte, status, errorMsg string, changed *bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJobResponse", ctx, jobID, hostname, responseData, status, errorMsg, changed)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJobResponse indicates an expected call of WriteJobResponse.
func (mr *MockJobClientMockRecorder) WriteJobResponse(ctx, jobID, hostname, responseData, status, errorMsg, changed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJobResponse", reflect.TypeOf((*MockJobClient)(nil).WriteJobResponse), ctx, jobID, hostname, responseData, status, errorMsg, changed)
}

// WriteStatusEvent mocks base method.
func (m *MockJobClient) WriteStatusEvent(ctx context.Context, jobID, event, hostname string, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteStatusEvent", ctx, jobID, event, hostname, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteStatusEvent indicates an expected call of WriteStatusEvent.
func (mr *MockJobClientMockRecorder) WriteStatusEvent(ctx, jobID, event, hostname, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteStatusEvent", reflect.TypeOf((*MockJobClient)(nil).WriteStatusEvent), ctx, jobID, event, hostname, data)
}
