// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/job/client (interfaces: JobClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
	client "github.com/osapi-io/nats-client/pkg/client"
	job "github.com/retr0h/osapi/internal/job"
	client0 "github.com/retr0h/osapi/internal/job/client"
	dns "github.com/retr0h/osapi/internal/provider/network/dns"
	ping "github.com/retr0h/osapi/internal/provider/network/ping"
)

// MockJobClient is a mock of JobClient interface.
type MockJobClient struct {
	ctrl     *gomock.Controller
	recorder *MockJobClientMockRecorder
}

// MockJobClientMockRecorder is the mock recorder for MockJobClient.
type MockJobClientMockRecorder struct {
	mock *MockJobClient
}

// NewMockJobClient creates a new mock instance.
func NewMockJobClient(ctrl *gomock.Controller) *MockJobClient {
	mock := &MockJobClient{ctrl: ctrl}
	mock.recorder = &MockJobClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobClient) EXPECT() *MockJobClientMockRecorder {
	return m.recorder
}

// ConsumeJobs mocks base method.
func (m *MockJobClient) ConsumeJobs(arg0 context.Context, arg1, arg2 string, arg3 func(jetstream.Msg) error, arg4 *client.ConsumeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeJobs", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeJobs indicates an expected call of ConsumeJobs.
func (mr *MockJobClientMockRecorder) ConsumeJobs(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeJobs", reflect.TypeOf((*MockJobClient)(nil).ConsumeJobs), arg0, arg1, arg2, arg3, arg4)
}

// CreateJob mocks base method.
func (m *MockJobClient) CreateJob(arg0 context.Context, arg1 map[string]interface{}, arg2 string) (*client0.CreateJobResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", arg0, arg1, arg2)
	ret0, _ := ret[0].(*client0.CreateJobResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobClientMockRecorder) CreateJob(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobClient)(nil).CreateJob), arg0, arg1, arg2)
}

// CreateOrUpdateConsumer mocks base method.
func (m *MockJobClient) CreateOrUpdateConsumer(arg0 context.Context, arg1 string, arg2 jetstream.ConsumerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateConsumer", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateConsumer indicates an expected call of CreateOrUpdateConsumer.
func (mr *MockJobClientMockRecorder) CreateOrUpdateConsumer(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateConsumer", reflect.TypeOf((*MockJobClient)(nil).CreateOrUpdateConsumer), arg0, arg1, arg2)
}

// DeleteJob mocks base method.
func (m *MockJobClient) DeleteJob(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockJobClientMockRecorder) DeleteJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockJobClient)(nil).DeleteJob), arg0, arg1)
}

// GetJobData mocks base method.
func (m *MockJobClient) GetJobData(arg0 context.Context, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobData", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobData indicates an expected call of GetJobData.
func (mr *MockJobClientMockRecorder) GetJobData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobData", reflect.TypeOf((*MockJobClient)(nil).GetJobData), arg0, arg1)
}

// GetJobStatus mocks base method.
func (m *MockJobClient) GetJobStatus(arg0 context.Context, arg1 string) (*job.QueuedJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStatus", arg0, arg1)
	ret0, _ := ret[0].(*job.QueuedJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobStatus indicates an expected call of GetJobStatus.
func (mr *MockJobClientMockRecorder) GetJobStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStatus", reflect.TypeOf((*MockJobClient)(nil).GetJobStatus), arg0, arg1)
}

// GetQueueStats mocks base method.
func (m *MockJobClient) GetQueueStats(arg0 context.Context) (*job.QueueStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueueStats", arg0)
	ret0, _ := ret[0].(*job.QueueStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQueueStats indicates an expected call of GetQueueStats.
func (mr *MockJobClientMockRecorder) GetQueueStats(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueueStats", reflect.TypeOf((*MockJobClient)(nil).GetQueueStats), arg0)
}

// ListJobs mocks base method.
func (m *MockJobClient) ListJobs(arg0 context.Context, arg1 string, arg2, arg3 int) (*client0.ListJobsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*client0.ListJobsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobClientMockRecorder) ListJobs(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobClient)(nil).ListJobs), arg0, arg1, arg2, arg3)
}

// ListWorkers mocks base method.
func (m *MockJobClient) ListWorkers(arg0 context.Context) (string, []job.WorkerInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWorkers", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]job.WorkerInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWorkers indicates an expected call of ListWorkers.
func (mr *MockJobClientMockRecorder) ListWorkers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWorkers", reflect.TypeOf((*MockJobClient)(nil).ListWorkers), arg0)
}

// ModifyNetworkDNS mocks base method.
func (m *MockJobClient) ModifyNetworkDNS(arg0 context.Context, arg1 string, arg2, arg3 []string, arg4 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyNetworkDNS", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ModifyNetworkDNS indicates an expected call of ModifyNetworkDNS.
func (mr *MockJobClientMockRecorder) ModifyNetworkDNS(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyNetworkDNS", reflect.TypeOf((*MockJobClient)(nil).ModifyNetworkDNS), arg0, arg1, arg2, arg3, arg4)
}

// ModifyNetworkDNSAll mocks base method.
func (m *MockJobClient) ModifyNetworkDNSAll(arg0 context.Context, arg1, arg2 []string, arg3 string) (string, map[string]error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyNetworkDNSAll", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ModifyNetworkDNSAll indicates an expected call of ModifyNetworkDNSAll.
func (mr *MockJobClientMockRecorder) ModifyNetworkDNSAll(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyNetworkDNSAll", reflect.TypeOf((*MockJobClient)(nil).ModifyNetworkDNSAll), arg0, arg1, arg2, arg3)
}

// ModifyNetworkDNSAny mocks base method.
func (m *MockJobClient) ModifyNetworkDNSAny(arg0 context.Context, arg1, arg2 []string, arg3 string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyNetworkDNSAny", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ModifyNetworkDNSAny indicates an expected call of ModifyNetworkDNSAny.
func (mr *MockJobClientMockRecorder) ModifyNetworkDNSAny(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyNetworkDNSAny", reflect.TypeOf((*MockJobClient)(nil).ModifyNetworkDNSAny), arg0, arg1, arg2, arg3)
}

// ModifyNetworkDNSBroadcast mocks base method.
func (m *MockJobClient) ModifyNetworkDNSBroadcast(arg0 context.Context, arg1 string, arg2, arg3 []string, arg4 string) (string, map[string]error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModifyNetworkDNSBroadcast", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ModifyNetworkDNSBroadcast indicates an expected call of ModifyNetworkDNSBroadcast.
func (mr *MockJobClientMockRecorder) ModifyNetworkDNSBroadcast(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyNetworkDNSBroadcast", reflect.TypeOf((*MockJobClient)(nil).ModifyNetworkDNSBroadcast), arg0, arg1, arg2, arg3, arg4)
}

// QueryNetworkDNS mocks base method.
func (m *MockJobClient) QueryNetworkDNS(arg0 context.Context, arg1, arg2 string) (string, *dns.Config, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNetworkDNS", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*dns.Config)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// QueryNetworkDNS indicates an expected call of QueryNetworkDNS.
func (mr *MockJobClientMockRecorder) QueryNetworkDNS(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNetworkDNS", reflect.TypeOf((*MockJobClient)(nil).QueryNetworkDNS), arg0, arg1, arg2)
}

// QueryNetworkDNSAll mocks base method.
func (m *MockJobClient) QueryNetworkDNSAll(arg0 context.Context, arg1 string) (string, map[string]*dns.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNetworkDNSAll", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*dns.Config)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryNetworkDNSAll indicates an expected call of QueryNetworkDNSAll.
func (mr *MockJobClientMockRecorder) QueryNetworkDNSAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNetworkDNSAll", reflect.TypeOf((*MockJobClient)(nil).QueryNetworkDNSAll), arg0, arg1)
}

// QueryNetworkDNSBroadcast mocks base method.
func (m *MockJobClient) QueryNetworkDNSBroadcast(arg0 context.Context, arg1, arg2 string) (string, map[string]*dns.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNetworkDNSBroadcast", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*dns.Config)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryNetworkDNSBroadcast indicates an expected call of QueryNetworkDNSBroadcast.
func (mr *MockJobClientMockRecorder) QueryNetworkDNSBroadcast(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNetworkDNSBroadcast", reflect.TypeOf((*MockJobClient)(nil).QueryNetworkDNSBroadcast), arg0, arg1, arg2)
}

// QueryNetworkPing mocks base method.
func (m *MockJobClient) QueryNetworkPing(arg0 context.Context, arg1, arg2 string) (string, *ping.Result, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNetworkPing", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*ping.Result)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// QueryNetworkPing indicates an expected call of QueryNetworkPing.
func (mr *MockJobClientMockRecorder) QueryNetworkPing(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNetworkPing", reflect.TypeOf((*MockJobClient)(nil).QueryNetworkPing), arg0, arg1, arg2)
}

// QueryNetworkPingAll mocks base method.
func (m *MockJobClient) QueryNetworkPingAll(arg0 context.Context, arg1 string) (string, map[string]*ping.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNetworkPingAll", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*ping.Result)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryNetworkPingAll indicates an expected call of QueryNetworkPingAll.
func (mr *MockJobClientMockRecorder) QueryNetworkPingAll(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNetworkPingAll", reflect.TypeOf((*MockJobClient)(nil).QueryNetworkPingAll), arg0, arg1)
}

// QueryNetworkPingAny mocks base method.
func (m *MockJobClient) QueryNetworkPingAny(arg0 context.Context, arg1 string) (string, *ping.Result, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNetworkPingAny", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*ping.Result)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// QueryNetworkPingAny indicates an expected call of QueryNetworkPingAny.
func (mr *MockJobClientMockRecorder) QueryNetworkPingAny(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNetworkPingAny", reflect.TypeOf((*MockJobClient)(nil).QueryNetworkPingAny), arg0, arg1)
}

// QueryNetworkPingBroadcast mocks base method.
func (m *MockJobClient) QueryNetworkPingBroadcast(arg0 context.Context, arg1, arg2 string) (string, map[string]*ping.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryNetworkPingBroadcast", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]*ping.Result)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryNetworkPingBroadcast indicates an expected call of QueryNetworkPingBroadcast.
func (mr *MockJobClientMockRecorder) QueryNetworkPingBroadcast(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryNetworkPingBroadcast", reflect.TypeOf((*MockJobClient)(nil).QueryNetworkPingBroadcast), arg0, arg1, arg2)
}

// QuerySystemHostname mocks base method.
func (m *MockJobClient) QuerySystemHostname(arg0 context.Context, arg1 string) (string, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySystemHostname", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// QuerySystemHostname indicates an expected call of QuerySystemHostname.
func (mr *MockJobClientMockRecorder) QuerySystemHostname(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySystemHostname", reflect.TypeOf((*MockJobClient)(nil).QuerySystemHostname), arg0, arg1)
}

// QuerySystemHostnameAll mocks base method.
func (m *MockJobClient) QuerySystemHostnameAll(arg0 context.Context) (string, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySystemHostnameAll", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QuerySystemHostnameAll indicates an expected call of QuerySystemHostnameAll.
func (mr *MockJobClientMockRecorder) QuerySystemHostnameAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySystemHostnameAll", reflect.TypeOf((*MockJobClient)(nil).QuerySystemHostnameAll), arg0)
}

// QuerySystemHostnameBroadcast mocks base method.
func (m *MockJobClient) QuerySystemHostnameBroadcast(arg0 context.Context, arg1 string) (string, map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySystemHostnameBroadcast", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(map[string]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QuerySystemHostnameBroadcast indicates an expected call of QuerySystemHostnameBroadcast.
func (mr *MockJobClientMockRecorder) QuerySystemHostnameBroadcast(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySystemHostnameBroadcast", reflect.TypeOf((*MockJobClient)(nil).QuerySystemHostnameBroadcast), arg0, arg1)
}

// QuerySystemStatus mocks base method.
func (m *MockJobClient) QuerySystemStatus(arg0 context.Context, arg1 string) (string, *job.SystemStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySystemStatus", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*job.SystemStatusResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QuerySystemStatus indicates an expected call of QuerySystemStatus.
func (mr *MockJobClientMockRecorder) QuerySystemStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySystemStatus", reflect.TypeOf((*MockJobClient)(nil).QuerySystemStatus), arg0, arg1)
}

// QuerySystemStatusAll mocks base method.
func (m *MockJobClient) QuerySystemStatusAll(arg0 context.Context) (string, []*job.SystemStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySystemStatusAll", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]*job.SystemStatusResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QuerySystemStatusAll indicates an expected call of QuerySystemStatusAll.
func (mr *MockJobClientMockRecorder) QuerySystemStatusAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySystemStatusAll", reflect.TypeOf((*MockJobClient)(nil).QuerySystemStatusAll), arg0)
}

// QuerySystemStatusAny mocks base method.
func (m *MockJobClient) QuerySystemStatusAny(arg0 context.Context) (string, *job.SystemStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySystemStatusAny", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*job.SystemStatusResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QuerySystemStatusAny indicates an expected call of QuerySystemStatusAny.
func (mr *MockJobClientMockRecorder) QuerySystemStatusAny(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySystemStatusAny", reflect.TypeOf((*MockJobClient)(nil).QuerySystemStatusAny), arg0)
}

// QuerySystemStatusBroadcast mocks base method.
func (m *MockJobClient) QuerySystemStatusBroadcast(arg0 context.Context, arg1 string) (string, []*job.SystemStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuerySystemStatusBroadcast", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]*job.SystemStatusResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QuerySystemStatusBroadcast indicates an expected call of QuerySystemStatusBroadcast.
func (mr *MockJobClientMockRecorder) QuerySystemStatusBroadcast(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuerySystemStatusBroadcast", reflect.TypeOf((*MockJobClient)(nil).QuerySystemStatusBroadcast), arg0, arg1)
}

// RetryJob mocks base method.
func (m *MockJobClient) RetryJob(arg0 context.Context, arg1, arg2 string) (*client0.CreateJobResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryJob", arg0, arg1, arg2)
	ret0, _ := ret[0].(*client0.CreateJobResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetryJob indicates an expected call of RetryJob.
func (mr *MockJobClientMockRecorder) RetryJob(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryJob", reflect.TypeOf((*MockJobClient)(nil).RetryJob), arg0, arg1, arg2)
}

// WriteJobResponse mocks base method.
func (m *MockJobClient) WriteJobResponse(arg0 context.Context, arg1, arg2 string, arg3 []byte, arg4, arg5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJobResponse", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJobResponse indicates an expected call of WriteJobResponse.
func (mr *MockJobClientMockRecorder) WriteJobResponse(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJobResponse", reflect.TypeOf((*MockJobClient)(nil).WriteJobResponse), arg0, arg1, arg2, arg3, arg4, arg5)
}

// WriteStatusEvent mocks base method.
func (m *MockJobClient) WriteStatusEvent(arg0 context.Context, arg1, arg2, arg3 string, arg4 map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteStatusEvent", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteStatusEvent indicates an expected call of WriteStatusEvent.
func (mr *MockJobClientMockRecorder) WriteStatusEvent(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteStatusEvent", reflect.TypeOf((*MockJobClient)(nil).WriteStatusEvent), arg0, arg1, arg2, arg3, arg4)
}
