// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/messaging (interfaces: NATSClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
	client "github.com/osapi-io/nats-client/pkg/client"
)

// MockNATSClient is a mock of NATSClient interface.
type MockNATSClient struct {
	ctrl     *gomock.Controller
	recorder *MockNATSClientMockRecorder
}

// MockNATSClientMockRecorder is the mock recorder for MockNATSClient.
type MockNATSClientMockRecorder struct {
	mock *MockNATSClient
}

// NewMockNATSClient creates a new mock instance.
func NewMockNATSClient(ctrl *gomock.Controller) *MockNATSClient {
	mock := &MockNATSClient{ctrl: ctrl}
	mock.recorder = &MockNATSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSClient) EXPECT() *MockNATSClientMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockNATSClient) Connect() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect")
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockNATSClientMockRecorder) Connect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockNATSClient)(nil).Connect))
}

// ConsumeMessages mocks base method.
func (m *MockNATSClient) ConsumeMessages(arg0 context.Context, arg1, arg2 string, arg3 client.JetStreamMessageHandler, arg4 *client.ConsumeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeMessages", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeMessages indicates an expected call of ConsumeMessages.
func (mr *MockNATSClientMockRecorder) ConsumeMessages(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMessages", reflect.TypeOf((*MockNATSClient)(nil).ConsumeMessages), arg0, arg1, arg2, arg3, arg4)
}

// CreateOrUpdateConsumerWithConfig mocks base method.
func (m *MockNATSClient) CreateOrUpdateConsumerWithConfig(arg0 context.Context, arg1 string, arg2 jetstream.ConsumerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateConsumerWithConfig", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateConsumerWithConfig indicates an expected call of CreateOrUpdateConsumerWithConfig.
func (mr *MockNATSClientMockRecorder) CreateOrUpdateConsumerWithConfig(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateConsumerWithConfig", reflect.TypeOf((*MockNATSClient)(nil).CreateOrUpdateConsumerWithConfig), arg0, arg1, arg2)
}

// CreateOrUpdateJetStreamWithConfig mocks base method.
func (m *MockNATSClient) CreateOrUpdateJetStreamWithConfig(arg0 context.Context, arg1 jetstream.StreamConfig, arg2 ...jetstream.ConsumerConfig) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrUpdateJetStreamWithConfig", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateJetStreamWithConfig indicates an expected call of CreateOrUpdateJetStreamWithConfig.
func (mr *MockNATSClientMockRecorder) CreateOrUpdateJetStreamWithConfig(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateJetStreamWithConfig", reflect.TypeOf((*MockNATSClient)(nil).CreateOrUpdateJetStreamWithConfig), varargs...)
}

// CreateOrUpdateKVBucket mocks base method.
func (m *MockNATSClient) CreateOrUpdateKVBucket(arg0 context.Context, arg1 string) (jetstream.KeyValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateKVBucket", arg0, arg1)
	ret0, _ := ret[0].(jetstream.KeyValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateKVBucket indicates an expected call of CreateOrUpdateKVBucket.
func (mr *MockNATSClientMockRecorder) CreateOrUpdateKVBucket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateKVBucket", reflect.TypeOf((*MockNATSClient)(nil).CreateOrUpdateKVBucket), arg0, arg1)
}

// CreateOrUpdateKVBucketWithConfig mocks base method.
func (m *MockNATSClient) CreateOrUpdateKVBucketWithConfig(arg0 context.Context, arg1 jetstream.KeyValueConfig) (jetstream.KeyValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateKVBucketWithConfig", arg0, arg1)
	ret0, _ := ret[0].(jetstream.KeyValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrUpdateKVBucketWithConfig indicates an expected call of CreateOrUpdateKVBucketWithConfig.
func (mr *MockNATSClientMockRecorder) CreateOrUpdateKVBucketWithConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateKVBucketWithConfig", reflect.TypeOf((*MockNATSClient)(nil).CreateOrUpdateKVBucketWithConfig), arg0, arg1)
}

// CreateOrUpdateStreamWithConfig mocks base method.
func (m *MockNATSClient) CreateOrUpdateStreamWithConfig(arg0 context.Context, arg1 jetstream.StreamConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateStreamWithConfig", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateStreamWithConfig indicates an expected call of CreateOrUpdateStreamWithConfig.
func (mr *MockNATSClientMockRecorder) CreateOrUpdateStreamWithConfig(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateStreamWithConfig", reflect.TypeOf((*MockNATSClient)(nil).CreateOrUpdateStreamWithConfig), arg0, arg1)
}

// GetStreamInfo mocks base method.
func (m *MockNATSClient) GetStreamInfo(arg0 context.Context, arg1 string) (*jetstream.StreamInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamInfo", arg0, arg1)
	ret0, _ := ret[0].(*jetstream.StreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamInfo indicates an expected call of GetStreamInfo.
func (mr *MockNATSClientMockRecorder) GetStreamInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamInfo", reflect.TypeOf((*MockNATSClient)(nil).GetStreamInfo), arg0, arg1)
}

// KVDelete mocks base method.
func (m *MockNATSClient) KVDelete(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KVDelete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// KVDelete indicates an expected call of KVDelete.
func (mr *MockNATSClientMockRecorder) KVDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KVDelete", reflect.TypeOf((*MockNATSClient)(nil).KVDelete), arg0, arg1)
}

// KVGet mocks base method.
func (m *MockNATSClient) KVGet(arg0, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KVGet", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KVGet indicates an expected call of KVGet.
func (mr *MockNATSClientMockRecorder) KVGet(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KVGet", reflect.TypeOf((*MockNATSClient)(nil).KVGet), arg0, arg1)
}

// KVKeys mocks base method.
func (m *MockNATSClient) KVKeys(arg0 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KVKeys", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KVKeys indicates an expected call of KVKeys.
func (mr *MockNATSClientMockRecorder) KVKeys(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KVKeys", reflect.TypeOf((*MockNATSClient)(nil).KVKeys), arg0)
}

// KVPut mocks base method.
func (m *MockNATSClient) KVPut(arg0, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KVPut", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// KVPut indicates an expected call of KVPut.
func (mr *MockNATSClientMockRecorder) KVPut(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KVPut", reflect.TypeOf((*MockNATSClient)(nil).KVPut), arg0, arg1, arg2)
}

// Publish mocks base method.
func (m *MockNATSClient) Publish(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNATSClientMockRecorder) Publish(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNATSClient)(nil).Publish), arg0, arg1, arg2)
}
