// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/job/client (interfaces: NATSClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	jetstream "github.com/nats-io/nats.go/jetstream"
	client "github.com/osapi-io/nats-client/pkg/client"
)

// MockNATSClient is a mock of NATSClient interface.
type MockNATSClient struct {
	ctrl     *gomock.Controller
	recorder *MockNATSClientMockRecorder
}

// MockNATSClientMockRecorder is the mock recorder for MockNATSClient.
type MockNATSClientMockRecorder struct {
	mock *MockNATSClient
}

// NewMockNATSClient creates a new mock instance.
func NewMockNATSClient(ctrl *gomock.Controller) *MockNATSClient {
	mock := &MockNATSClient{ctrl: ctrl}
	mock.recorder = &MockNATSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSClient) EXPECT() *MockNATSClientMockRecorder {
	return m.recorder
}

// ConsumeMessages mocks base method.
func (m *MockNATSClient) ConsumeMessages(arg0 context.Context, arg1, arg2 string, arg3 client.JetStreamMessageHandler, arg4 *client.ConsumeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeMessages", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConsumeMessages indicates an expected call of ConsumeMessages.
func (mr *MockNATSClientMockRecorder) ConsumeMessages(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeMessages", reflect.TypeOf((*MockNATSClient)(nil).ConsumeMessages), arg0, arg1, arg2, arg3, arg4)
}

// CreateOrUpdateConsumerWithConfig mocks base method.
func (m *MockNATSClient) CreateOrUpdateConsumerWithConfig(arg0 context.Context, arg1 string, arg2 jetstream.ConsumerConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateConsumerWithConfig", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateConsumerWithConfig indicates an expected call of CreateOrUpdateConsumerWithConfig.
func (mr *MockNATSClientMockRecorder) CreateOrUpdateConsumerWithConfig(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateConsumerWithConfig", reflect.TypeOf((*MockNATSClient)(nil).CreateOrUpdateConsumerWithConfig), arg0, arg1, arg2)
}

// GetStreamInfo mocks base method.
func (m *MockNATSClient) GetStreamInfo(arg0 context.Context, arg1 string) (*jetstream.StreamInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamInfo", arg0, arg1)
	ret0, _ := ret[0].(*jetstream.StreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamInfo indicates an expected call of GetStreamInfo.
func (mr *MockNATSClientMockRecorder) GetStreamInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamInfo", reflect.TypeOf((*MockNATSClient)(nil).GetStreamInfo), arg0, arg1)
}

// KVPut mocks base method.
func (m *MockNATSClient) KVPut(arg0, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KVPut", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// KVPut indicates an expected call of KVPut.
func (mr *MockNATSClientMockRecorder) KVPut(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KVPut", reflect.TypeOf((*MockNATSClient)(nil).KVPut), arg0, arg1, arg2)
}

// Publish mocks base method.
func (m *MockNATSClient) Publish(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNATSClientMockRecorder) Publish(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNATSClient)(nil).Publish), arg0, arg1, arg2)
}
