// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osapi-io/osapi/internal/job/client (interfaces: PKISigner)
//
// Generated by this command:
//
//	mockgen -destination=./pki_signer.gen.go -package=mocks github.com/osapi-io/osapi/internal/job/client PKISigner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ed25519 "crypto/ed25519"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPKISigner is a mock of PKISigner interface.
type MockPKISigner struct {
	ctrl     *gomock.Controller
	recorder *MockPKISignerMockRecorder
	isgomock struct{}
}

// MockPKISignerMockRecorder is the mock recorder for MockPKISigner.
type MockPKISignerMockRecorder struct {
	mock *MockPKISigner
}

// NewMockPKISigner creates a new mock instance.
func NewMockPKISigner(ctrl *gomock.Controller) *MockPKISigner {
	mock := &MockPKISigner{ctrl: ctrl}
	mock.recorder = &MockPKISignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPKISigner) EXPECT() *MockPKISignerMockRecorder {
	return m.recorder
}

// ControllerPublicKey mocks base method.
func (m *MockPKISigner) ControllerPublicKey() ed25519.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ControllerPublicKey")
	ret0, _ := ret[0].(ed25519.PublicKey)
	return ret0
}

// ControllerPublicKey indicates an expected call of ControllerPublicKey.
func (mr *MockPKISignerMockRecorder) ControllerPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerPublicKey", reflect.TypeOf((*MockPKISigner)(nil).ControllerPublicKey))
}

// Fingerprint mocks base method.
func (m *MockPKISigner) Fingerprint() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fingerprint")
	ret0, _ := ret[0].(string)
	return ret0
}

// Fingerprint indicates an expected call of Fingerprint.
func (mr *MockPKISignerMockRecorder) Fingerprint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fingerprint", reflect.TypeOf((*MockPKISigner)(nil).Fingerprint))
}

// Sign mocks base method.
func (m *MockPKISigner) Sign(data []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", data)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Sign indicates an expected call of Sign.
func (mr *MockPKISignerMockRecorder) Sign(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockPKISigner)(nil).Sign), data)
}
