// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/controller/api/agent (interfaces: EnrollmentManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	enrollment "github.com/retr0h/osapi/internal/controller/enrollment"
)

// MockEnrollmentManager is a mock of EnrollmentManager interface.
type MockEnrollmentManager struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentManagerMockRecorder
}

// MockEnrollmentManagerMockRecorder is the mock recorder for MockEnrollmentManager.
type MockEnrollmentManagerMockRecorder struct {
	mock *MockEnrollmentManager
}

// NewMockEnrollmentManager creates a new mock instance.
func NewMockEnrollmentManager(ctrl *gomock.Controller) *MockEnrollmentManager {
	mock := &MockEnrollmentManager{ctrl: ctrl}
	mock.recorder = &MockEnrollmentManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentManager) EXPECT() *MockEnrollmentManagerMockRecorder {
	return m.recorder
}

// AcceptByFingerprint mocks base method.
func (m *MockEnrollmentManager) AcceptByFingerprint(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptByFingerprint", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptByFingerprint indicates an expected call of AcceptByFingerprint.
func (mr *MockEnrollmentManagerMockRecorder) AcceptByFingerprint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptByFingerprint", reflect.TypeOf((*MockEnrollmentManager)(nil).AcceptByFingerprint), arg0, arg1)
}

// AcceptByHostname mocks base method.
func (m *MockEnrollmentManager) AcceptByHostname(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptByHostname", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptByHostname indicates an expected call of AcceptByHostname.
func (mr *MockEnrollmentManagerMockRecorder) AcceptByHostname(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptByHostname", reflect.TypeOf((*MockEnrollmentManager)(nil).AcceptByHostname), arg0, arg1)
}

// ListPending mocks base method.
func (m *MockEnrollmentManager) ListPending(arg0 context.Context) ([]enrollment.PendingAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", arg0)
	ret0, _ := ret[0].([]enrollment.PendingAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockEnrollmentManagerMockRecorder) ListPending(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockEnrollmentManager)(nil).ListPending), arg0)
}

// RejectByHostname mocks base method.
func (m *MockEnrollmentManager) RejectByHostname(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectByHostname", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectByHostname indicates an expected call of RejectByHostname.
func (mr *MockEnrollmentManagerMockRecorder) RejectByHostname(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectByHostname", reflect.TypeOf((*MockEnrollmentManager)(nil).RejectByHostname), arg0, arg1, arg2)
}
