// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/controller/api/agent (interfaces: EnrollmentManager)
//
// Generated by this command:
//
//	mockgen -destination=agent.gen.go -package=mocks github.com/retr0h/osapi/internal/controller/api/agent EnrollmentManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	enrollment "github.com/retr0h/osapi/internal/controller/enrollment"
	gomock "go.uber.org/mock/gomock"
)

// MockEnrollmentManager is a mock of EnrollmentManager interface.
type MockEnrollmentManager struct {
	ctrl     *gomock.Controller
	recorder *MockEnrollmentManagerMockRecorder
	isgomock struct{}
}

// MockEnrollmentManagerMockRecorder is the mock recorder for MockEnrollmentManager.
type MockEnrollmentManagerMockRecorder struct {
	mock *MockEnrollmentManager
}

// NewMockEnrollmentManager creates a new mock instance.
func NewMockEnrollmentManager(ctrl *gomock.Controller) *MockEnrollmentManager {
	mock := &MockEnrollmentManager{ctrl: ctrl}
	mock.recorder = &MockEnrollmentManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnrollmentManager) EXPECT() *MockEnrollmentManagerMockRecorder {
	return m.recorder
}

// AcceptByFingerprint mocks base method.
func (m *MockEnrollmentManager) AcceptByFingerprint(ctx context.Context, fingerprint string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptByFingerprint", ctx, fingerprint)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptByFingerprint indicates an expected call of AcceptByFingerprint.
func (mr *MockEnrollmentManagerMockRecorder) AcceptByFingerprint(ctx, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptByFingerprint", reflect.TypeOf((*MockEnrollmentManager)(nil).AcceptByFingerprint), ctx, fingerprint)
}

// AcceptByHostname mocks base method.
func (m *MockEnrollmentManager) AcceptByHostname(ctx context.Context, hostname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptByHostname", ctx, hostname)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptByHostname indicates an expected call of AcceptByHostname.
func (mr *MockEnrollmentManagerMockRecorder) AcceptByHostname(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptByHostname", reflect.TypeOf((*MockEnrollmentManager)(nil).AcceptByHostname), ctx, hostname)
}

// ListPending mocks base method.
func (m *MockEnrollmentManager) ListPending(ctx context.Context) ([]enrollment.PendingAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx)
	ret0, _ := ret[0].([]enrollment.PendingAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockEnrollmentManagerMockRecorder) ListPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockEnrollmentManager)(nil).ListPending), ctx)
}

// RejectByHostname mocks base method.
func (m *MockEnrollmentManager) RejectByHostname(ctx context.Context, hostname, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectByHostname", ctx, hostname, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectByHostname indicates an expected call of RejectByHostname.
func (mr *MockEnrollmentManagerMockRecorder) RejectByHostname(ctx, hostname, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectByHostname", reflect.TypeOf((*MockEnrollmentManager)(nil).RejectByHostname), ctx, hostname, reason)
}
