// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	health "github.com/retr0h/osapi/internal/controller/api/health"
)

// MockChecker is a mock of Checker interface.
type MockChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCheckerMockRecorder
}

// MockCheckerMockRecorder is the mock recorder for MockChecker.
type MockCheckerMockRecorder struct {
	mock *MockChecker
}

// NewMockChecker creates a new mock instance.
func NewMockChecker(ctrl *gomock.Controller) *MockChecker {
	mock := &MockChecker{ctrl: ctrl}
	mock.recorder = &MockCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChecker) EXPECT() *MockCheckerMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockChecker) CheckHealth(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockCheckerMockRecorder) CheckHealth(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockChecker)(nil).CheckHealth), ctx)
}

// MockMetricsProvider is a mock of MetricsProvider interface.
type MockMetricsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsProviderMockRecorder
}

// MockMetricsProviderMockRecorder is the mock recorder for MockMetricsProvider.
type MockMetricsProviderMockRecorder struct {
	mock *MockMetricsProvider
}

// NewMockMetricsProvider creates a new mock instance.
func NewMockMetricsProvider(ctrl *gomock.Controller) *MockMetricsProvider {
	mock := &MockMetricsProvider{ctrl: ctrl}
	mock.recorder = &MockMetricsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsProvider) EXPECT() *MockMetricsProviderMockRecorder {
	return m.recorder
}

// GetAgentStats mocks base method.
func (m *MockMetricsProvider) GetAgentStats(ctx context.Context) (*health.AgentMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentStats", ctx)
	ret0, _ := ret[0].(*health.AgentMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentStats indicates an expected call of GetAgentStats.
func (mr *MockMetricsProviderMockRecorder) GetAgentStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentStats", reflect.TypeOf((*MockMetricsProvider)(nil).GetAgentStats), ctx)
}

// GetComponentRegistry mocks base method.
func (m *MockMetricsProvider) GetComponentRegistry(ctx context.Context) ([]health.ComponentEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponentRegistry", ctx)
	ret0, _ := ret[0].([]health.ComponentEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponentRegistry indicates an expected call of GetComponentRegistry.
func (mr *MockMetricsProviderMockRecorder) GetComponentRegistry(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponentRegistry", reflect.TypeOf((*MockMetricsProvider)(nil).GetComponentRegistry), ctx)
}

// GetJobStats mocks base method.
func (m *MockMetricsProvider) GetJobStats(ctx context.Context) (*health.JobMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobStats", ctx)
	ret0, _ := ret[0].(*health.JobMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobStats indicates an expected call of GetJobStats.
func (mr *MockMetricsProviderMockRecorder) GetJobStats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobStats", reflect.TypeOf((*MockMetricsProvider)(nil).GetJobStats), ctx)
}

// GetKVInfo mocks base method.
func (m *MockMetricsProvider) GetKVInfo(ctx context.Context) ([]health.KVMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKVInfo", ctx)
	ret0, _ := ret[0].([]health.KVMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKVInfo indicates an expected call of GetKVInfo.
func (mr *MockMetricsProviderMockRecorder) GetKVInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKVInfo", reflect.TypeOf((*MockMetricsProvider)(nil).GetKVInfo), ctx)
}

// GetNATSInfo mocks base method.
func (m *MockMetricsProvider) GetNATSInfo(ctx context.Context) (*health.NATSMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNATSInfo", ctx)
	ret0, _ := ret[0].(*health.NATSMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNATSInfo indicates an expected call of GetNATSInfo.
func (mr *MockMetricsProviderMockRecorder) GetNATSInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNATSInfo", reflect.TypeOf((*MockMetricsProvider)(nil).GetNATSInfo), ctx)
}

// GetObjectStoreInfo mocks base method.
func (m *MockMetricsProvider) GetObjectStoreInfo(ctx context.Context) ([]health.ObjectStoreMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectStoreInfo", ctx)
	ret0, _ := ret[0].([]health.ObjectStoreMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectStoreInfo indicates an expected call of GetObjectStoreInfo.
func (mr *MockMetricsProviderMockRecorder) GetObjectStoreInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectStoreInfo", reflect.TypeOf((*MockMetricsProvider)(nil).GetObjectStoreInfo), ctx)
}

// GetStreamInfo mocks base method.
func (m *MockMetricsProvider) GetStreamInfo(ctx context.Context) ([]health.StreamMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamInfo", ctx)
	ret0, _ := ret[0].([]health.StreamMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamInfo indicates an expected call of GetStreamInfo.
func (mr *MockMetricsProviderMockRecorder) GetStreamInfo(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamInfo", reflect.TypeOf((*MockMetricsProvider)(nil).GetStreamInfo), ctx)
}
