// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nats-io/nats.go/jetstream (interfaces: MessageBatch)
//
// Generated by this command:
//
//	mockgen -destination=message_batch.gen.go -package=mocks github.com/nats-io/nats.go/jetstream MessageBatch
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageBatch is a mock of MessageBatch interface.
type MockMessageBatch struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBatchMockRecorder
	isgomock struct{}
}

// MockMessageBatchMockRecorder is the mock recorder for MockMessageBatch.
type MockMessageBatchMockRecorder struct {
	mock *MockMessageBatch
}

// NewMockMessageBatch creates a new mock instance.
func NewMockMessageBatch(ctrl *gomock.Controller) *MockMessageBatch {
	mock := &MockMessageBatch{ctrl: ctrl}
	mock.recorder = &MockMessageBatchMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBatch) EXPECT() *MockMessageBatchMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockMessageBatch) Error() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Error")
	ret0, _ := ret[0].(error)
	return ret0
}

// Error indicates an expected call of Error.
func (mr *MockMessageBatchMockRecorder) Error() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockMessageBatch)(nil).Error))
}

// Messages mocks base method.
func (m *MockMessageBatch) Messages() <-chan jetstream.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Messages")
	ret0, _ := ret[0].(<-chan jetstream.Msg)
	return ret0
}

// Messages indicates an expected call of Messages.
func (mr *MockMessageBatchMockRecorder) Messages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Messages", reflect.TypeOf((*MockMessageBatch)(nil).Messages))
}
