// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	netplan "github.com/retr0h/osapi/internal/provider/network/netplan"
)

// MockInterfaceProvider is a mock of InterfaceProvider interface.
type MockInterfaceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceProviderMockRecorder
}

// MockInterfaceProviderMockRecorder is the mock recorder for MockInterfaceProvider.
type MockInterfaceProviderMockRecorder struct {
	mock *MockInterfaceProvider
}

// NewMockInterfaceProvider creates a new mock instance.
func NewMockInterfaceProvider(ctrl *gomock.Controller) *MockInterfaceProvider {
	mock := &MockInterfaceProvider{ctrl: ctrl}
	mock.recorder = &MockInterfaceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterfaceProvider) EXPECT() *MockInterfaceProviderMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInterfaceProvider) Create(ctx context.Context, entry netplan.InterfaceEntry) (*netplan.InterfaceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entry)
	ret0, _ := ret[0].(*netplan.InterfaceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInterfaceProviderMockRecorder) Create(ctx, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInterfaceProvider)(nil).Create), ctx, entry)
}

// Delete mocks base method.
func (m *MockInterfaceProvider) Delete(ctx context.Context, name string) (*netplan.InterfaceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(*netplan.InterfaceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockInterfaceProviderMockRecorder) Delete(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInterfaceProvider)(nil).Delete), ctx, name)
}

// Get mocks base method.
func (m *MockInterfaceProvider) Get(ctx context.Context, name string) (*netplan.InterfaceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*netplan.InterfaceEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockInterfaceProviderMockRecorder) Get(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockInterfaceProvider)(nil).Get), ctx, name)
}

// List mocks base method.
func (m *MockInterfaceProvider) List(ctx context.Context) ([]netplan.InterfaceEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]netplan.InterfaceEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInterfaceProviderMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInterfaceProvider)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockInterfaceProvider) Update(ctx context.Context, entry netplan.InterfaceEntry) (*netplan.InterfaceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entry)
	ret0, _ := ret[0].(*netplan.InterfaceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockInterfaceProviderMockRecorder) Update(ctx, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockInterfaceProvider)(nil).Update), ctx, entry)
}

// MockRouteProvider is a mock of RouteProvider interface.
type MockRouteProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRouteProviderMockRecorder
}

// MockRouteProviderMockRecorder is the mock recorder for MockRouteProvider.
type MockRouteProviderMockRecorder struct {
	mock *MockRouteProvider
}

// NewMockRouteProvider creates a new mock instance.
func NewMockRouteProvider(ctrl *gomock.Controller) *MockRouteProvider {
	mock := &MockRouteProvider{ctrl: ctrl}
	mock.recorder = &MockRouteProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteProvider) EXPECT() *MockRouteProviderMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRouteProvider) Create(ctx context.Context, entry netplan.RouteEntry) (*netplan.RouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entry)
	ret0, _ := ret[0].(*netplan.RouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRouteProviderMockRecorder) Create(ctx, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRouteProvider)(nil).Create), ctx, entry)
}

// Delete mocks base method.
func (m *MockRouteProvider) Delete(ctx context.Context, interfaceName string) (*netplan.RouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, interfaceName)
	ret0, _ := ret[0].(*netplan.RouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRouteProviderMockRecorder) Delete(ctx, interfaceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRouteProvider)(nil).Delete), ctx, interfaceName)
}

// Get mocks base method.
func (m *MockRouteProvider) Get(ctx context.Context, interfaceName string) (*netplan.RouteEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, interfaceName)
	ret0, _ := ret[0].(*netplan.RouteEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRouteProviderMockRecorder) Get(ctx, interfaceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRouteProvider)(nil).Get), ctx, interfaceName)
}

// List mocks base method.
func (m *MockRouteProvider) List(ctx context.Context) ([]netplan.RouteListEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]netplan.RouteListEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRouteProviderMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRouteProvider)(nil).List), ctx)
}

// Update mocks base method.
func (m *MockRouteProvider) Update(ctx context.Context, entry netplan.RouteEntry) (*netplan.RouteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entry)
	ret0, _ := ret[0].(*netplan.RouteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRouteProviderMockRecorder) Update(ctx, entry interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRouteProvider)(nil).Update), ctx, entry)
}
