// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

// MockStateKeyValue is a mock of StateKeyValue interface.
type MockStateKeyValue struct {
	ctrl     *gomock.Controller
	recorder *MockStateKeyValueMockRecorder
	isgomock struct{}
}

// MockStateKeyValueMockRecorder is the mock recorder for MockStateKeyValue.
type MockStateKeyValueMockRecorder struct {
	mock *MockStateKeyValue
}

// NewMockStateKeyValue creates a new mock instance.
func NewMockStateKeyValue(ctrl *gomock.Controller) *MockStateKeyValue {
	mock := &MockStateKeyValue{ctrl: ctrl}
	mock.recorder = &MockStateKeyValueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateKeyValue) EXPECT() *MockStateKeyValueMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockStateKeyValue) Get(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(jetstream.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStateKeyValueMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStateKeyValue)(nil).Get), ctx, key)
}

// Keys mocks base method.
func (m *MockStateKeyValue) Keys(ctx context.Context, opts ...jetstream.WatchOpt) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Keys", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockStateKeyValueMockRecorder) Keys(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockStateKeyValue)(nil).Keys), varargs...)
}

// MockObjectStoreManager is a mock of ObjectStoreManager interface.
type MockObjectStoreManager struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStoreManagerMockRecorder
	isgomock struct{}
}

// MockObjectStoreManagerMockRecorder is the mock recorder for MockObjectStoreManager.
type MockObjectStoreManagerMockRecorder struct {
	mock *MockObjectStoreManager
}

// NewMockObjectStoreManager creates a new mock instance.
func NewMockObjectStoreManager(ctrl *gomock.Controller) *MockObjectStoreManager {
	mock := &MockObjectStoreManager{ctrl: ctrl}
	mock.recorder = &MockObjectStoreManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStoreManager) EXPECT() *MockObjectStoreManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockObjectStoreManager) Delete(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectStoreManagerMockRecorder) Delete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectStoreManager)(nil).Delete), ctx, name)
}

// GetBytes mocks base method.
func (m *MockObjectStoreManager) GetBytes(ctx context.Context, name string, opts ...jetstream.GetObjectOpt) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBytes", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBytes indicates an expected call of GetBytes.
func (mr *MockObjectStoreManagerMockRecorder) GetBytes(ctx, name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBytes", reflect.TypeOf((*MockObjectStoreManager)(nil).GetBytes), varargs...)
}

// GetInfo mocks base method.
func (m *MockObjectStoreManager) GetInfo(ctx context.Context, name string, opts ...jetstream.GetObjectInfoOpt) (*jetstream.ObjectInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInfo", varargs...)
	ret0, _ := ret[0].(*jetstream.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockObjectStoreManagerMockRecorder) GetInfo(ctx, name any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockObjectStoreManager)(nil).GetInfo), varargs...)
}

// List mocks base method.
func (m *MockObjectStoreManager) List(ctx context.Context, opts ...jetstream.ListObjectsOpt) ([]*jetstream.ObjectInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*jetstream.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockObjectStoreManagerMockRecorder) List(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockObjectStoreManager)(nil).List), varargs...)
}

// Put mocks base method.
func (m *MockObjectStoreManager) Put(ctx context.Context, meta jetstream.ObjectMeta, reader io.Reader) (*jetstream.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, meta, reader)
	ret0, _ := ret[0].(*jetstream.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockObjectStoreManagerMockRecorder) Put(ctx, meta, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockObjectStoreManager)(nil).Put), ctx, meta, reader)
}

// PutBytes mocks base method.
func (m *MockObjectStoreManager) PutBytes(ctx context.Context, name string, data []byte) (*jetstream.ObjectInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutBytes", ctx, name, data)
	ret0, _ := ret[0].(*jetstream.ObjectInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutBytes indicates an expected call of PutBytes.
func (mr *MockObjectStoreManagerMockRecorder) PutBytes(ctx, name, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutBytes", reflect.TypeOf((*MockObjectStoreManager)(nil).PutBytes), ctx, name, data)
}
