// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dns "github.com/retr0h/osapi/internal/provider/network/netplan/dns"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// DeleteNetplanConfig mocks base method.
func (m *MockProvider) DeleteNetplanConfig(interfaceName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNetplanConfig", interfaceName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteNetplanConfig indicates an expected call of DeleteNetplanConfig.
func (mr *MockProviderMockRecorder) DeleteNetplanConfig(interfaceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNetplanConfig", reflect.TypeOf((*MockProvider)(nil).DeleteNetplanConfig), interfaceName)
}

// GetResolvConfByInterface mocks base method.
func (m *MockProvider) GetResolvConfByInterface(interfaceName string) (*dns.GetResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResolvConfByInterface", interfaceName)
	ret0, _ := ret[0].(*dns.GetResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResolvConfByInterface indicates an expected call of GetResolvConfByInterface.
func (mr *MockProviderMockRecorder) GetResolvConfByInterface(interfaceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResolvConfByInterface", reflect.TypeOf((*MockProvider)(nil).GetResolvConfByInterface), interfaceName)
}

// UpdateResolvConfByInterface mocks base method.
func (m *MockProvider) UpdateResolvConfByInterface(servers, searchDomains []string, interfaceName string, overrideDHCP bool) (*dns.UpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResolvConfByInterface", servers, searchDomains, interfaceName, overrideDHCP)
	ret0, _ := ret[0].(*dns.UpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResolvConfByInterface indicates an expected call of UpdateResolvConfByInterface.
func (mr *MockProviderMockRecorder) UpdateResolvConfByInterface(servers, searchDomains, interfaceName, overrideDHCP any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResolvConfByInterface", reflect.TypeOf((*MockProvider)(nil).UpdateResolvConfByInterface), servers, searchDomains, interfaceName, overrideDHCP)
}
