// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package user

import (
	"fmt"

	sha512crypt "github.com/GehirnInc/crypt/sha512_crypt"
)

// hashPassword is a package-level variable so tests can inject a hashing
// failure. See export_test.go for the setter/reset pair.
var hashPassword = defaultHashPassword

// generateHash is the underlying crypt library call behind
// defaultHashPassword, held in a package-level variable so tests can inject
// a failure from it directly. See export_test.go for the setter/reset pair.
var generateHash = sha512crypt.New().Generate

// defaultHashPassword hashes a plaintext password into a SHA-512 crypt hash
// ("$6$<salt>$<hash>"), the format /etc/shadow and "chpasswd -e" accept. The
// salt is generated by the underlying library from crypto/rand.
//
// The plaintext password is hashed here, at the controller, and never placed
// in job data: only the resulting hash travels to the agent and provider.
func defaultHashPassword(
	password string,
) (string, error) {
	// A nil salt tells generateHash to create its own, valid by construction,
	// so this error is not reachable through any password value in
	// production. The check is kept because generateHash's signature can
	// fail, and SetGenerateHashFn (see export_test.go) injects a failure to
	// cover it.
	hash, err := generateHash([]byte(password), nil)
	if err != nil {
		return "", fmt.Errorf("hash password: %w", err)
	}

	return hash, nil
}
