// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/controller/enrollment (interfaces: NATSSubscriber,PKIProvider)

// Package mocks is a generated GoMock package.
package mocks

import (
	ed25519 "crypto/ed25519"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nats "github.com/nats-io/nats.go"
)

// MockNATSSubscriber is a mock of NATSSubscriber interface.
type MockNATSSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockNATSSubscriberMockRecorder
}

// MockNATSSubscriberMockRecorder is the mock recorder for MockNATSSubscriber.
type MockNATSSubscriberMockRecorder struct {
	mock *MockNATSSubscriber
}

// NewMockNATSSubscriber creates a new mock instance.
func NewMockNATSSubscriber(ctrl *gomock.Controller) *MockNATSSubscriber {
	mock := &MockNATSSubscriber{ctrl: ctrl}
	mock.recorder = &MockNATSSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSSubscriber) EXPECT() *MockNATSSubscriberMockRecorder {
	return m.recorder
}

// PublishCore mocks base method.
func (m *MockNATSSubscriber) PublishCore(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCore indicates an expected call of PublishCore.
func (mr *MockNATSSubscriberMockRecorder) PublishCore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCore", reflect.TypeOf((*MockNATSSubscriber)(nil).PublishCore), arg0, arg1)
}

// Subscribe mocks base method.
func (m *MockNATSSubscriber) Subscribe(arg0 string, arg1 nats.MsgHandler) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNATSSubscriberMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNATSSubscriber)(nil).Subscribe), arg0, arg1)
}

// MockPKIProvider is a mock of PKIProvider interface.
type MockPKIProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPKIProviderMockRecorder
}

// MockPKIProviderMockRecorder is the mock recorder for MockPKIProvider.
type MockPKIProviderMockRecorder struct {
	mock *MockPKIProvider
}

// NewMockPKIProvider creates a new mock instance.
func NewMockPKIProvider(ctrl *gomock.Controller) *MockPKIProvider {
	mock := &MockPKIProvider{ctrl: ctrl}
	mock.recorder = &MockPKIProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPKIProvider) EXPECT() *MockPKIProviderMockRecorder {
	return m.recorder
}

// PublicKey mocks base method.
func (m *MockPKIProvider) PublicKey() ed25519.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKey")
	ret0, _ := ret[0].(ed25519.PublicKey)
	return ret0
}

// PublicKey indicates an expected call of PublicKey.
func (mr *MockPKIProviderMockRecorder) PublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKey", reflect.TypeOf((*MockPKIProvider)(nil).PublicKey))
}
