// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/agent (interfaces: NATSPublisher)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNATSPublisher is a mock of NATSPublisher interface.
type MockNATSPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockNATSPublisherMockRecorder
}

// MockNATSPublisherMockRecorder is the mock recorder for MockNATSPublisher.
type MockNATSPublisherMockRecorder struct {
	mock *MockNATSPublisher
}

// NewMockNATSPublisher creates a new mock instance.
func NewMockNATSPublisher(ctrl *gomock.Controller) *MockNATSPublisher {
	mock := &MockNATSPublisher{ctrl: ctrl}
	mock.recorder = &MockNATSPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSPublisher) EXPECT() *MockNATSPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockNATSPublisher) Publish(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNATSPublisherMockRecorder) Publish(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNATSPublisher)(nil).Publish), arg0, arg1, arg2)
}
