// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/agent (interfaces: NATSPublisher)
//
// Generated by this command:
//
//	mockgen -destination=nats_publisher.gen.go -package=mocks github.com/retr0h/osapi/internal/agent NATSPublisher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	nats "github.com/nats-io/nats.go"
	gomock "go.uber.org/mock/gomock"
)

// MockNATSPublisher is a mock of NATSPublisher interface.
type MockNATSPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockNATSPublisherMockRecorder
	isgomock struct{}
}

// MockNATSPublisherMockRecorder is the mock recorder for MockNATSPublisher.
type MockNATSPublisherMockRecorder struct {
	mock *MockNATSPublisher
}

// NewMockNATSPublisher creates a new mock instance.
func NewMockNATSPublisher(ctrl *gomock.Controller) *MockNATSPublisher {
	mock := &MockNATSPublisher{ctrl: ctrl}
	mock.recorder = &MockNATSPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSPublisher) EXPECT() *MockNATSPublisherMockRecorder {
	return m.recorder
}

// PublishCore mocks base method.
func (m *MockNATSPublisher) PublishCore(subject string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCore", subject, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCore indicates an expected call of PublishCore.
func (mr *MockNATSPublisherMockRecorder) PublishCore(subject, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCore", reflect.TypeOf((*MockNATSPublisher)(nil).PublishCore), subject, data)
}

// Subscribe mocks base method.
func (m *MockNATSPublisher) Subscribe(subject string, handler nats.MsgHandler) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", subject, handler)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNATSPublisherMockRecorder) Subscribe(subject, handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNATSPublisher)(nil).Subscribe), subject, handler)
}
