// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/retr0h/osapi/internal/agent (interfaces: NATSPublisher)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nats "github.com/nats-io/nats.go"
)

// MockNATSPublisher is a mock of NATSPublisher interface.
type MockNATSPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockNATSPublisherMockRecorder
}

// MockNATSPublisherMockRecorder is the mock recorder for MockNATSPublisher.
type MockNATSPublisherMockRecorder struct {
	mock *MockNATSPublisher
}

// NewMockNATSPublisher creates a new mock instance.
func NewMockNATSPublisher(ctrl *gomock.Controller) *MockNATSPublisher {
	mock := &MockNATSPublisher{ctrl: ctrl}
	mock.recorder = &MockNATSPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATSPublisher) EXPECT() *MockNATSPublisherMockRecorder {
	return m.recorder
}

// PublishCore mocks base method.
func (m *MockNATSPublisher) PublishCore(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishCore", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishCore indicates an expected call of PublishCore.
func (mr *MockNATSPublisherMockRecorder) PublishCore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishCore", reflect.TypeOf((*MockNATSPublisher)(nil).PublishCore), arg0, arg1)
}

// Subscribe mocks base method.
func (m *MockNATSPublisher) Subscribe(arg0 string, arg1 nats.MsgHandler) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNATSPublisherMockRecorder) Subscribe(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNATSPublisher)(nil).Subscribe), arg0, arg1)
}
