// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package dns_test

import (
	"log/slog"
	"os"
	"testing"

	"github.com/avfs/avfs"
	"github.com/avfs/avfs/vfs/memfs"
	"github.com/stretchr/testify/suite"

	"github.com/retr0h/osapi/internal/provider"
	"github.com/retr0h/osapi/internal/provider/network/dns"
)

type DebianDockerPublicTestSuite struct {
	suite.Suite

	logger *slog.Logger
	fs     avfs.VFS
}

func (s *DebianDockerPublicTestSuite) SetupTest() {
	s.logger = slog.New(slog.NewTextHandler(os.Stdout, nil))
	s.fs = memfs.New()
}

func (s *DebianDockerPublicTestSuite) SetupSubTest() {
	s.SetupTest()
}

func (s *DebianDockerPublicTestSuite) TestGetResolvConfByInterface() {
	tests := []struct {
		name          string
		setupFS       func(fs avfs.VFS)
		interfaceName string
		want          *dns.GetResult
		wantErr       bool
		errContains   string
	}{
		{
			name: "when resolv.conf has servers and search domains",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"# Generated by Docker\n"+
						"nameserver 127.0.0.11\n"+
						"nameserver 8.8.8.8\n"+
						"search example.com local.lan\n"+
						"options ndots:0\n",
				), 0o644)
			},
			interfaceName: "eth0",
			want: &dns.GetResult{
				DNSServers:    []string{"127.0.0.11", "8.8.8.8"},
				SearchDomains: []string{"example.com", "local.lan"},
			},
		},
		{
			name: "when resolv.conf has only nameservers",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"nameserver 8.8.8.8\n"+
						"nameserver 8.8.4.4\n",
				), 0o644)
			},
			interfaceName: "eth0",
			want: &dns.GetResult{
				DNSServers:    []string{"8.8.8.8", "8.8.4.4"},
				SearchDomains: []string{"."},
			},
		},
		{
			name: "when resolv.conf has IPv6 nameservers",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"nameserver 2001:4860:4860::8888\n"+
						"nameserver 2001:4860:4860::8844\n",
				), 0o644)
			},
			interfaceName: "any-interface",
			want: &dns.GetResult{
				DNSServers:    []string{"2001:4860:4860::8888", "2001:4860:4860::8844"},
				SearchDomains: []string{"."},
			},
		},
		{
			name: "when resolv.conf has comments and blank lines",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"# This is a comment\n"+
						"\n"+
						"nameserver 1.1.1.1\n"+
						"# Another comment\n"+
						"search test.local\n"+
						"\n",
				), 0o644)
			},
			interfaceName: "eth0",
			want: &dns.GetResult{
				DNSServers:    []string{"1.1.1.1"},
				SearchDomains: []string{"test.local"},
			},
		},
		{
			name: "when resolv.conf does not exist",
			setupFS: func(_ avfs.VFS) {
				// Don't create the file
			},
			interfaceName: "eth0",
			wantErr:       true,
			errContains:   "failed to read /etc/resolv.conf",
		},
		{
			name: "when resolv.conf is empty",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(""), 0o644)
			},
			interfaceName: "eth0",
			want: &dns.GetResult{
				DNSServers:    nil,
				SearchDomains: []string{"."},
			},
		},
		{
			name: "when interface parameter is ignored",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"nameserver 10.0.0.1\n",
				), 0o644)
			},
			interfaceName: "completely-ignored",
			want: &dns.GetResult{
				DNSServers:    []string{"10.0.0.1"},
				SearchDomains: []string{"."},
			},
		},
		{
			name: "when multiple search lines uses last one",
			setupFS: func(fs avfs.VFS) {
				_ = fs.MkdirAll("/etc", 0o755)
				_ = fs.WriteFile("/etc/resolv.conf", []byte(
					"nameserver 8.8.8.8\n"+
						"search first.com\n"+
						"search second.com third.com\n",
				), 0o644)
			},
			interfaceName: "eth0",
			want: &dns.GetResult{
				DNSServers:    []string{"8.8.8.8"},
				SearchDomains: []string{"second.com", "third.com"},
			},
		},
	}

	for _, tc := range tests {
		s.Run(tc.name, func() {
			tc.setupFS(s.fs)

			p := dns.NewDebianDockerProvider(s.logger, s.fs)
			got, err := p.GetResolvConfByInterface(tc.interfaceName)

			if tc.wantErr {
				s.Error(err)
				s.Contains(err.Error(), tc.errContains)
			} else {
				s.NoError(err)
				s.Equal(tc.want, got)
			}
		})
	}
}

func (s *DebianDockerPublicTestSuite) TestUpdateResolvConfByInterface() {
	tests := []struct {
		name string
	}{
		{
			name: "returns ErrUnsupported for container",
		},
	}

	for _, tt := range tests {
		s.Run(tt.name, func() {
			p := dns.NewDebianDockerProvider(s.logger, s.fs)
			result, err := p.UpdateResolvConfByInterface(
				[]string{"8.8.8.8"},
				[]string{"example.com"},
				"eth0",
			)

			s.Error(err)
			s.Nil(result)
			s.ErrorIs(err, provider.ErrUnsupported)
		})
	}
}

func TestDebianDockerPublicTestSuite(t *testing.T) {
	suite.Run(t, new(DebianDockerPublicTestSuite))
}
