// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=provider.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	syscall "syscall"

	process "github.com/retr0h/osapi/internal/provider/node/process"
	process0 "github.com/shirou/gopsutil/v4/process"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProvider) Get(ctx context.Context, pid int) (*process.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, pid)
	ret0, _ := ret[0].(*process.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProviderMockRecorder) Get(ctx, pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProvider)(nil).Get), ctx, pid)
}

// List mocks base method.
func (m *MockProvider) List(ctx context.Context) ([]process.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]process.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProviderMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProvider)(nil).List), ctx)
}

// Signal mocks base method.
func (m *MockProvider) Signal(ctx context.Context, pid int, signal string) (*process.SignalResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", ctx, pid, signal)
	ret0, _ := ret[0].(*process.SignalResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockProviderMockRecorder) Signal(ctx, pid, signal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockProvider)(nil).Signal), ctx, pid, signal)
}

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CPUPercent mocks base method.
func (m *MockQuerier) CPUPercent() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CPUPercent")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CPUPercent indicates an expected call of CPUPercent.
func (mr *MockQuerierMockRecorder) CPUPercent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CPUPercent", reflect.TypeOf((*MockQuerier)(nil).CPUPercent))
}

// Cmdline mocks base method.
func (m *MockQuerier) Cmdline() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cmdline")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cmdline indicates an expected call of Cmdline.
func (mr *MockQuerierMockRecorder) Cmdline() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cmdline", reflect.TypeOf((*MockQuerier)(nil).Cmdline))
}

// CreateTime mocks base method.
func (m *MockQuerier) CreateTime() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTime")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTime indicates an expected call of CreateTime.
func (mr *MockQuerierMockRecorder) CreateTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTime", reflect.TypeOf((*MockQuerier)(nil).CreateTime))
}

// MemoryInfo mocks base method.
func (m *MockQuerier) MemoryInfo() (*process0.MemoryInfoStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemoryInfo")
	ret0, _ := ret[0].(*process0.MemoryInfoStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemoryInfo indicates an expected call of MemoryInfo.
func (mr *MockQuerierMockRecorder) MemoryInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemoryInfo", reflect.TypeOf((*MockQuerier)(nil).MemoryInfo))
}

// MemoryPercent mocks base method.
func (m *MockQuerier) MemoryPercent() (float32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemoryPercent")
	ret0, _ := ret[0].(float32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemoryPercent indicates an expected call of MemoryPercent.
func (mr *MockQuerierMockRecorder) MemoryPercent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemoryPercent", reflect.TypeOf((*MockQuerier)(nil).MemoryPercent))
}

// Name mocks base method.
func (m *MockQuerier) Name() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Name indicates an expected call of Name.
func (mr *MockQuerierMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockQuerier)(nil).Name))
}

// Status mocks base method.
func (m *MockQuerier) Status() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockQuerierMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockQuerier)(nil).Status))
}

// Username mocks base method.
func (m *MockQuerier) Username() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Username")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Username indicates an expected call of Username.
func (mr *MockQuerierMockRecorder) Username() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Username", reflect.TypeOf((*MockQuerier)(nil).Username))
}

// MockLister is a mock of Lister interface.
type MockLister struct {
	ctrl     *gomock.Controller
	recorder *MockListerMockRecorder
	isgomock struct{}
}

// MockListerMockRecorder is the mock recorder for MockLister.
type MockListerMockRecorder struct {
	mock *MockLister
}

// NewMockLister creates a new mock instance.
func NewMockLister(ctrl *gomock.Controller) *MockLister {
	mock := &MockLister{ctrl: ctrl}
	mock.recorder = &MockListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLister) EXPECT() *MockListerMockRecorder {
	return m.recorder
}

// NewProcess mocks base method.
func (m *MockLister) NewProcess(pid int32) (process.Querier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewProcess", pid)
	ret0, _ := ret[0].(process.Querier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewProcess indicates an expected call of NewProcess.
func (mr *MockListerMockRecorder) NewProcess(pid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewProcess", reflect.TypeOf((*MockLister)(nil).NewProcess), pid)
}

// Processes mocks base method.
func (m *MockLister) Processes() ([]process.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Processes")
	ret0, _ := ret[0].([]process.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Processes indicates an expected call of Processes.
func (mr *MockListerMockRecorder) Processes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Processes", reflect.TypeOf((*MockLister)(nil).Processes))
}

// MockSignaler is a mock of Signaler interface.
type MockSignaler struct {
	ctrl     *gomock.Controller
	recorder *MockSignalerMockRecorder
	isgomock struct{}
}

// MockSignalerMockRecorder is the mock recorder for MockSignaler.
type MockSignalerMockRecorder struct {
	mock *MockSignaler
}

// NewMockSignaler creates a new mock instance.
func NewMockSignaler(ctrl *gomock.Controller) *MockSignaler {
	mock := &MockSignaler{ctrl: ctrl}
	mock.recorder = &MockSignalerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignaler) EXPECT() *MockSignalerMockRecorder {
	return m.recorder
}

// Kill mocks base method.
func (m *MockSignaler) Kill(pid int, sig syscall.Signal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kill", pid, sig)
	ret0, _ := ret[0].(error)
	return ret0
}

// Kill indicates an expected call of Kill.
func (mr *MockSignalerMockRecorder) Kill(pid, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kill", reflect.TypeOf((*MockSignaler)(nil).Kill), pid, sig)
}
