// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=provider.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	power "github.com/retr0h/osapi/internal/provider/node/power"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Reboot mocks base method.
func (m *MockProvider) Reboot(ctx context.Context, opts power.Opts) (*power.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reboot", ctx, opts)
	ret0, _ := ret[0].(*power.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reboot indicates an expected call of Reboot.
func (mr *MockProviderMockRecorder) Reboot(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reboot", reflect.TypeOf((*MockProvider)(nil).Reboot), ctx, opts)
}

// Shutdown mocks base method.
func (m *MockProvider) Shutdown(ctx context.Context, opts power.Opts) (*power.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx, opts)
	ret0, _ := ret[0].(*power.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockProviderMockRecorder) Shutdown(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockProvider)(nil).Shutdown), ctx, opts)
}
