import { defineConfig } from 'orval'

export default defineConfig({
  osapi: {
    input: {
      target: './src/sdk/gen/api.yaml',
    },
    output: {
      target: './src/sdk/gen/client.ts',
      schemas: './src/sdk/gen/schemas',
      client: 'fetch',
      mode: 'tags-split',
      baseUrl: false,
      override: {
        header: ({ title, version } = {}) => [
          'Generated by orval 🍺',
          'Do not edit manually.',
          ...(title ? [title] : []),
          ...(version ? [`OpenAPI spec version: ${version}`] : []),
        ],
        mutator: {
          path: './src/sdk/fetch.ts',
          name: 'apiFetch',
        },
      },
    },
  },
})
