// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=provider.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	log "github.com/retr0h/osapi/internal/provider/node/log"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// ListSources mocks base method.
func (m *MockProvider) ListSources(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSources", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSources indicates an expected call of ListSources.
func (mr *MockProviderMockRecorder) ListSources(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSources", reflect.TypeOf((*MockProvider)(nil).ListSources), ctx)
}

// Query mocks base method.
func (m *MockProvider) Query(ctx context.Context, opts log.QueryOpts) ([]log.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, opts)
	ret0, _ := ret[0].([]log.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockProviderMockRecorder) Query(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockProvider)(nil).Query), ctx, opts)
}

// QueryUnit mocks base method.
func (m *MockProvider) QueryUnit(ctx context.Context, unit string, opts log.QueryOpts) ([]log.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryUnit", ctx, unit, opts)
	ret0, _ := ret[0].([]log.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryUnit indicates an expected call of QueryUnit.
func (mr *MockProviderMockRecorder) QueryUnit(ctx, unit, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryUnit", reflect.TypeOf((*MockProvider)(nil).QueryUnit), ctx, unit, opts)
}
