// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	command "github.com/retr0h/osapi/internal/provider/command"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockProvider) Exec(params command.ExecParams) (*command.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec", params)
	ret0, _ := ret[0].(*command.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockProviderMockRecorder) Exec(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockProvider)(nil).Exec), params)
}

// Shell mocks base method.
func (m *MockProvider) Shell(params command.ShellParams) (*command.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shell", params)
	ret0, _ := ret[0].(*command.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shell indicates an expected call of Shell.
func (mr *MockProviderMockRecorder) Shell(params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shell", reflect.TypeOf((*MockProvider)(nil).Shell), params)
}
