---
name: Docusaurus Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - uses: oven-sh/setup-bun@v2
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Fetch justfiles
        run: just fetch
      - name: Test build website
        run: just docusaurus-build
