---
name: Go Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Fetch justfiles
        run: just fetch
      - name: Deps
        run: |
          just go::deps
          just react::deps
      - name: Build UI
        run: just react::build
      - name: Linux tuning
        run: just linux-tune
      - name: Integration
        run: just go::unit-int
